# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 824d3cc03933b2e42a619e7880841d21dfc4bb587337941ad956d6228012cbb0f34a0d9755d3a4a140e22c9eec8da5bc617d35cf5ee40d4acea6303e7511d332

test:
  secret_key_base: e9c5f5259f620bf68c73c9f3367eade0ac85373ad8fe42dc756a1d68d853a7f798a61bc624a2c805bff57f9417c1c9475f162c533c76eab97f388db1a389de7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
